# Generated by Django 6.0.3 on 2026-03-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_pedidos', models.IntegerField(default=0)),
                ('total_pagos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_productos', models.IntegerField(default=0)),
                ('clientes_nuevos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'db_table': 'dashboard',
                'unique_together': {('fecha',)},
            },
        ),
    ]
