# Generated by Django 4.2.16 on 2026-04-07 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_barrio_usuario_ciudad_usuario_codigo_postal_and_more'),
        ('pedidos', '0003_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_cliente', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
    ]
