# Generated by Django 4.2.16 on 2026-04-06 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_move_cliente_data'),
        ('pedidos', '0003_alter_pedido_cliente'),
        ('ventas', '0002_alter_venta_cliente'),
        ('clientes', '0004_cliente_barrio_cliente_numero_documento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
